# W3Schools, Python Try...Except
try:
    print(x)
except:
    print("Something else went wrong")
finally:
    print("The 'try except' is finished")
